version: '2'
services:
  twentyonepoints-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/twentyOnePoints/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=twentyOnePoints
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
